# Generated by Django 5.2.3 on 2025-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='local_recording_path',
            field=models.CharField(blank=True, help_text='Local path to stored recording', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='local_recording_url',
            field=models.CharField(blank=True, help_text='Local URL to access recording', max_length=500, null=True),
        ),
    ]
