# Generated by Django 5.2.3 on 2025-06-21 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_local_recording_path_call_local_recording_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_url', models.URLField(help_text='Twilio recording URL')),
                ('local_recording_path', models.CharField(blank=True, help_text='Local path to stored recording', max_length=500, null=True)),
                ('local_recording_url', models.CharField(blank=True, help_text='Local URL to access recording', max_length=500, null=True)),
                ('chunk_number', models.IntegerField(help_text='Order of this chunk in the call')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration of this chunk in seconds', null=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether this chunk has been processed by AI')),
                ('response_audio_url', models.URLField(blank=True, help_text='URL to AI response audio', null=True)),
                ('response_played', models.BooleanField(default=False, help_text='Whether AI response was played to caller')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_chunks', to='calls.call')),
            ],
            options={
                'verbose_name': 'Recording Chunk',
                'verbose_name_plural': 'Recording Chunks',
                'ordering': ['chunk_number'],
                'unique_together': {('call', 'chunk_number')},
            },
        ),
    ]
