# Generated by Django 5.2.3 on 2025-06-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_recordingchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='conversation_state',
            field=models.JSONField(blank=True, help_text='Conversation history for AI processing', null=True),
        ),
    ]
