# Generated by Django 5.2.3 on 2025-06-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_conversation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingchunk',
            name='language_code',
            field=models.CharField(blank=True, help_text='Language detected in transcription', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recordingchunk',
            name='risk_assessment_completed',
            field=models.BooleanField(default=False, help_text='Whether risk assessment has been completed for this chunk'),
        ),
        migrations.AddField(
            model_name='recordingchunk',
            name='transcription',
            field=models.TextField(blank=True, help_text='Transcription of this audio chunk', null=True),
        ),
    ]
