# Generated by Django 5.2.3 on 2025-06-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_conversation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='highest_risk_category',
            field=models.CharField(blank=True, help_text='Risk category that triggered the highest risk level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='highest_risk_level',
            field=models.CharField(blank=True, choices=[('no_risk', 'No Risk'), ('low_risk', 'Low Risk'), ('medium_risk', 'Medium Risk'), ('high_risk', 'High Risk'), ('alert', 'ALERT!')], help_text='Highest risk level detected across all recording chunks', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recordingchunk',
            name='risk_category',
            field=models.CharField(blank=True, help_text='Risk category identified in this chunk', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recordingchunk',
            name='risk_level',
            field=models.CharField(blank=True, help_text='Risk level for this chunk', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recordingchunk',
            name='risk_processed',
            field=models.BooleanField(default=False, help_text='Whether risk assessment has been completed'),
        ),
        migrations.AddField(
            model_name='recordingchunk',
            name='transcription',
            field=models.TextField(blank=True, help_text='Transcription of this chunk', null=True),
        ),
    ]
